### ISSUE TITLE
Newbie question - Can this be used to advertise an iBeacon?

### ISSUE THREAD

**Issue by saurabhnanda** [plow-technologies/ble#22]
I'm working on a side-project for which I'd like to use bluetooth for some proximity/location based features. Can I use the `ble` library to advertise an iBeacon from the server/Haskell, such that it can be read/scanned by an Android device on the other side?

**Comment by jkarni** [comment]
If the server is running Linux, then yes (this library only works with Linux).
As I understand it (which is not much), an iBeacon advertisement is just
a specific type of BLE advertisement. That said, you're mostly on your own in
figuring out the details, since I don't know much about iBeacon.

**Comment by saurabhnanda** [comment]
Thanks for the quick response @jkarni There is documentation on how to use bluez for an ibeacon advertisement, which should be easily translatable to the Haskell wrapper API, right?

**Comment by jkarni** [comment]
Yup. This in particular should be a good start:

https://scribles.net/creating-ibeacon-using-bluez-example-code-on-raspberry-pi/

**Comment by smurphy8** [comment]
Seems like we are good here?

**Comment by saurabhnanda** [comment]
Yes yes. Please close.
